# ⚠️ WARNING: Make sure the model you specify supports the Responses API format
# (i.e. the /v1/responses endpoint). Using unsupported models may result in
# runtime errors or failed requests.

[[providers]]
name = "openai"
key = "..."
endpoint = "https://api.openai.com/v1"

[[models]]
name = "gpt-4.1-nano"
provider = "openai"
model = "gpt-4.1-nano"
