[[providers]]
name = "openai"
key = "qwerty"
endpoint = "https://api.openai.com/v1"

[[providers]]
name = "gemini"
key = "your-gemini-api-key"
endpoint = "https://api.gemini.com/v1"

[[models]]
name = "gpt-4.1-nano"
provider = "openai"
model = "gpt-4.1-nano"

[[models]]
name = "gemini-2.5-pro"
provider = "gemini"
model = "gemini-2.5-pro"
